CREATE TABLE IF NOT EXISTS MEMBERS
(
  member_id     BIGINT       NOT NULL AUTO_INCREMENT,
  login_id      VARCHAR(50)  NOT NULL,
  password      VARCHAR(255) NOT NULL,
  nickname      VARCHAR(20)  NOT NULL,
  email         VARCHAR(255) NOT NULL,
  status        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
  last_login_at DATETIME              DEFAULT NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_MEMBER PRIMARY KEY (member_id),
  CONSTRAINT UK_MEMBER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ROLES
(
  role_id    BIGINT      NOT NULL AUTO_INCREMENT,
  role_name  VARCHAR(10) NOT NULL,
  created_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_ROLE PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS MEMBER_ROLE
(
  member_role_id BIGINT   NOT NULL AUTO_INCREMENT,
  member_id      BIGINT   NOT NULL,
  role_id        BIGINT   NOT NULL,
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_MEMBER_ROLE PRIMARY KEY (member_role_id),
  CONSTRAINT FK_MEMBER_ROLE_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBERS (member_id),
  CONSTRAINT FK_MEMBER_ROLE_ROLE FOREIGN KEY (role_id) REFERENCES ROLES (role_id)
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKENS
(
  token_id    BIGINT   NOT NULL AUTO_INCREMENT,
  member_id   BIGINT   NOT NULL,
  token_value CHAR(64) NOT NULL,
  expires_at  DATETIME NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (token_id),
  CONSTRAINT UK_REFRESH_TOKEN_VALUE UNIQUE (token_value),
  CONSTRAINT FK_REFRESH_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBERS (member_id)
);
